### ISSUE TITLE
[Setup] Modelo de Base de Datos

### ISSUE THREAD

**Issue by jjsanmartino03** [jjsanmartino03/faf#8]
Definir el modelo de base de datos. Esta tarea se deberá realizar en conjunto y debatiendo cada parte del esquema. El objetivo es llegar a una primera versión del modelo, incluyendo cada tabla, sus propiedades y sus relaciones.

**Comment by jjsanmartino03** [comment]
El modelo de datos se está realizando aquí https://drawsql.app/teams/chulianteam/diagrams/faf

**Comment by ivandietta** [comment]
**Para realizar pruebas del correcto funcionamiento de la base de datos realizamos varios inserts de prueba:**

- INSERT INTO `categories` VALUES (1,2023,1),(2,2024,1)
- INSERT INTO `crosses` VALUES (5,'2024-01-01',10,11),(6,'2024-01-02',12,13),(7,'2024-01-03',10,12),(8,'2024-01-04',11,13);
- INSERT INTO `matches` VALUES (9,1,5,13,15,1,2),(10,2,6,18,20,3,4),(11,1,7,13,17,1,3),(12,2,8,16,20,2,4);
- INSERT INTO `players` VALUES (121,'Player 1','active',13),(122,'Player 2','active',13),(123,'Player 3','active',13),(124,'Player 4','active',13),(125,'Player 5','active',13),(126,'Player 6','active',13),(127,'Player 7','active',13),(128,'Player 8','active',13),(129,'Player 9','active',13),(130,'Player 10','active',13),(131,'Player 11','active',15),(132,'Player 12','active',15),(133,'Player 13','active',15),(134,'Player 14','active',15),(135,'Player 15','active',15),(136,'Player 16','active',15),(137,'Player 17','active',15),(138,'Player 18','active',15),(139,'Player 19','active',15),(140,'Player 20','active',15),(141,'Player 21','active',17),(142,'Player 22','active',17),(143,'Player 23','active',17),(144,'Player 24','active',17),(145,'Player 25','active',17),(146,'Player 26','active',17),(147,'Player 27','active',17),(148,'Player 28','active',17),(149,'Player 29','active',17),(150,'Player 30','active',17),(151,'Player 31','active',19),(152,'Player 32','active',19),(153,'Player 33','active',19),(154,'Player 34','active',19),(155,'Player 35','active',19),(156,'Player 36','active',19),(157,'Player 37','active',19),(158,'Player 38','active',19),(159,'Player 39','active',19),(160,'Player 40','active',19);
- INSERT INTO `team_categories` VALUES (13,1,10),(14,2,10),(15,1,11),(16,2,11),(17,1,12),(18,2,12),(19,1,13),(20,2,13);
- INSERT INTO `teams` VALUES (10,'Team 1','https://example.com/logo1.png'),(11,'Team 2','https://example.com/logo2.png'),(12,'Team 3','https://example.com/logo3.png'),(13,'Team 4','https://example.com/logo4.png');
- INSERT INTO `validation` VALUES (1,'approved','https://example.com/photo1.png'),(2,'approved','https://example.com/photo2.png'),(3,'approved','https://example.com/photo3.png'),(4,'approved','https://example.com/photo4.png'),(5,'approved','https://example.com/photo5.png'),(6,'approved','https://example.com/photo6.png'),(7,'approved','https://example.com/photo7.png'),(8,'approved','https://example.com/photo8.png');
- INSERT INTO `validation_players` VALUES (1,121,1),(2,122,1),(3,123,1),(4,124,1),(5,125,1),(6,126,2),(7,127,2),(8,128,2),(9,129,2),(10,130,2),(11,131,3),(12,132,3),(13,133,3),(14,134,3),(15,135,3),(16,136,4),(17,137,4),(18,138,4),(19,139,4),(20,140,4),(21,141,5),(22,142,5),(23,143,5),(24,144,5),(25,145,5),(26,146,6),(27,147,6),(28,148,6),(29,149,6),(30,150,6),(31,151,7),(32,152,7),(33,153,7),(34,154,7),(35,155,7),(36,156,8),(37,157,8),(38,158,8),(39,159,8),(40,160,8);

**Luego realizamos los siguientes selects:**

- Todos los Equipos (Nombre y Logo)
SELECT `name`, `logo_url` FROM faf.teams;
- Todos los Partidos de un Equipo Específico en una Fecha Específica
SELECT c.`year` AS category_year, l.`name` AS local_team_name, l.`logo_url` AS local_team_logo, CASE WHEN m.`local_validation_id` IS NOT NULL THEN 'Validado' ELSE 'No Validado' END AS local_validation_status, v.`name` AS visitor_team_name, v.`logo_url` AS visitor_team_logo, CASE WHEN m.`visitor_validation_id` IS NOT NULL THEN 'Validado' ELSE 'No Validado' END AS visitor_validation_status FROM faf.matches m JOIN faf.team_categories tc1 ON m.local_team_category_id = tc1.id JOIN faf.teams l ON tc1.team_id = l.id JOIN faf.team_categories tc2 ON m.visitor_team_category_id = tc2.id JOIN faf.teams v ON tc2.team_id = v.id JOIN faf.crosses cr ON m.cross_id = cr.id JOIN faf.categories c ON tc1.category_id = c.id WHERE (l.`name` = 'Team 1' OR v.`name` = 'Team 1') AND cr.`date` = '2024-01-01';
- Un Equipo Específico y Todas las Categorías Existentes
SELECT t.`name` AS team_name, t.`logo_url` AS team_logo, c.`year` AS category_year FROM faf.team_categories tc JOIN faf.teams t ON tc.team_id = t.id JOIN faf.categories c ON tc.category_id = c.id WHERE t.`name` = 'Team 1';
- Lista de Jugadores de una Categoría de un Equipo Específico
SELECT p.`name` AS player_name, p.`status` AS player_status FROM faf.players p JOIN faf.team_categories tc ON p.team_category_id = tc.id JOIN faf.teams t ON tc.team_id = t.id WHERE t.`name` = 'Team 1' AND tc.category_id = (SELECT id FROM faf.categories WHERE year = 2023);
- Todos los Cruces (Nombre y Logo de los Equipos Locales y Visitantes, y Fecha del Cruce)
SELECT l.`name` AS local_team_name, l.`logo_url` AS local_team_logo, v.`name` AS visitor_team_name, v.`logo_url` AS visitor_team_logo, cr.`date` AS cross_date FROM faf.crosses cr JOIN faf.teams l ON cr.local_team_id = l.id JOIN faf.teams v ON cr.visitor_team_id = v.id;
